package webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.5
//
// Created by Quasar Development at 24-05-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class User extends AttributeContainer implements KvmSerializable
{
    
    public Address addressid;
    
    public String firstname;
    
    public Long id;
    
    public String lastname;
    
    public String password;
    
    public String phonenumber;
    
    public String profileimageURL;
    
    public String username;
    
    public String usertype;

    public User()
    {
    }

    public User(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("addressid"))
        {	
	        java.lang.Object j = soapObject.getProperty("addressid");
	        this.addressid = (Address)__envelope.get(j, Address.class);
        }
        if (soapObject.hasProperty("firstname"))
        {	
	        java.lang.Object obj = soapObject.getProperty("firstname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.firstname = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.firstname = (String)obj;
            }    
        }
        if (soapObject.hasProperty("id"))
        {	
	        java.lang.Object obj = soapObject.getProperty("id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.id = new Long(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Long){
                this.id = (Long)obj;
            }    
        }
        if (soapObject.hasProperty("lastname"))
        {	
	        java.lang.Object obj = soapObject.getProperty("lastname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.lastname = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.lastname = (String)obj;
            }    
        }
        if (soapObject.hasProperty("password"))
        {	
	        java.lang.Object obj = soapObject.getProperty("password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.password = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.password = (String)obj;
            }    
        }
        if (soapObject.hasProperty("phonenumber"))
        {	
	        java.lang.Object obj = soapObject.getProperty("phonenumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.phonenumber = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.phonenumber = (String)obj;
            }    
        }
        if (soapObject.hasProperty("profileimageURL"))
        {	
	        java.lang.Object obj = soapObject.getProperty("profileimageURL");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.profileimageURL = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.profileimageURL = (String)obj;
            }    
        }
        if (soapObject.hasProperty("username"))
        {	
	        java.lang.Object obj = soapObject.getProperty("username");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.username = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.username = (String)obj;
            }    
        }
        if (soapObject.hasProperty("usertype"))
        {	
	        java.lang.Object obj = soapObject.getProperty("usertype");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.usertype = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.usertype = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.addressid!=null?this.addressid:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.firstname!=null?this.firstname:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.lastname!=null?this.lastname:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.password!=null?this.password:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.phonenumber!=null?this.phonenumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.profileimageURL!=null?this.profileimageURL:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.username!=null?this.username:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.usertype!=null?this.usertype:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 9;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = Address.class;
            info.name = "addressid";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "firstname";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "id";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastname";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "password";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "phonenumber";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "profileimageURL";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "username";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usertype";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
